# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 598)
        MainWindow.setStyleSheet("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\nbackground-color : #C2E8FF;\n}")
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("#frame{background-color:#ffffff;border-radius:25px}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.label_logo = QtWidgets.QLabel(self.frame)
        self.label_logo.setEnabled(True)
        self.label_logo.setMaximumSize(QtCore.QSize(200, 100))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("fslappcode/icons/logo.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_logo.setObjectName("label_logo")

        self.horizontalLayout.addWidget(self.label_logo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)

        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setEnabled(True)
        
        font = QtGui.QFont()
        font.setFamily("Coolvetica Rg")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("#label {\ncolor : #192955;\n}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_translation = QtWidgets.QPushButton(self.frame)
        self.pushButton_translation.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_translation.setMaximumSize(QtCore.QSize(300, 300))
        self.pushButton_translation.setStyleSheet("""
                                            QPushButton {
                                                background-color : #C2E8FF;
                                                border: none;
                                                border-radius : 25px
                                            }
                                            QPushButton:hover {
                                                background-color : #A9D6FF;
                                            }
                                            """)
        self.pushButton_translation.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("fslappcode/icons/Frame 17.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_translation.setIcon(icon)
        self.pushButton_translation.setIconSize(QtCore.QSize(200, 200))
        self.pushButton_translation.setObjectName("pushButton_translation")
        self.horizontalLayout_3.addWidget(self.pushButton_translation)
        
        self.pushButton_learn = QtWidgets.QPushButton(self.frame)
        self.pushButton_learn.setMaximumSize(QtCore.QSize(300, 300))
        self.pushButton_learn.setStyleSheet("""
                                            QPushButton {
                                                background-color: #C2E8FF;
                                                border: none;
                                                border-radius : 25px
                                            }
                                            QPushButton:hover {
                                                background-color : #A9D6FF;
                                            }
                                            """)
        self.pushButton_learn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("fslappcode/icons/Frame 13.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_learn.setIcon(icon1)
        self.pushButton_learn.setIconSize(QtCore.QSize(180, 180))
        self.pushButton_learn.setObjectName("pushButton_learn")
        self.horizontalLayout_3.addWidget(self.pushButton_learn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        
        self.label_translation = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Coolvetica Rg")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_translation.setFont(font)
        self.label_translation.setStyleSheet("""
                                            QLabel { 
                                                color : #192955
                                            }
                                            """)
        self.label_translation.setAlignment(QtCore.Qt.AlignCenter)
        self.label_translation.setObjectName("label_translation")
        self.horizontalLayout_8.addWidget(self.label_translation)
        
        self.label_learn = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Coolvetica Rg")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_learn.setFont(font)
        self.label_learn.setStyleSheet("""
                                    QLabel {
                                        color : #192955
                                    }
                                    """)
        self.label_learn.setAlignment(QtCore.Qt.AlignCenter)
        self.label_learn.setObjectName("label_learn")
        self.horizontalLayout_8.addWidget(self.label_learn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_learn, self.pushButton_translation)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Translate and Learn Basic Filipino Sign Language"))
        self.label_translation.setText(_translate("MainWindow", "TRANSLATE"))
        self.label_learn.setText(_translate("MainWindow", "LEARN"))

if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
